site_name: 'XSLT 3.1 with examples'
site_url: 'https://xsltdev.com/'
site_description: 'XSLT 3.1 Documentation with examples'
site_author: 'xsltdev.com'
copyright: '&copy; 2019 - 2022, XSLT 3.1 Documentation and examples<br /><a href="https://t.me/xsltdev">Discuss in Telegram group</a>'

repo_name: 'Github'
repo_url: 'https://github.com/xsltdev/xsltdev.com'

theme:
    name: 'material'
    custom_dir: overrides
    palette:
        primary: 'green'
        accent: 'green'
    language: 'en'
    #    favicon: 'assets/images/favicon.ico'
    feature:
        - navigation.instant
        - navigation.tabs
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - announce.dismiss
    favicon: xslt.svg
    logo: xslt.svg

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: ⚓︎
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences

plugins:
    - search:
          separator: '[\s\-\:]+'
          prebuild_index: true
    - awesome-pages
    - section-index

extra:
    generator: false
    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/xsltdev
